image: docker

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test

cache:
  key: ${CI_JOB_NAME}
  paths:
    - vendor

before_script:
  - apk add --no-cache bash make py-pip
  - pip install docker-compose
  - docker -v && docker-compose -v

build:dependencies:
  stage: build
  script:
    - make up
    - docker-compose run --rm php composer install --prefer-dist

test:behat:
  stage: test
  script:
    - docker-compose run --rm php vendor/behat/behat/bin/behat

test:phpspec:
  stage: test
  script:
    - docker-compose run --rm php vendor/phpspec/phpspec/bin/phpspec run
