language: php

sudo: false

services:
  - docker

stages:
  - build
  - test

before_cache:
    - mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}' | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

cache:
  directories:
    - vendor
    - $HOME/docker

before_install:
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

install:
  - sudo curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - docker-compose --version

jobs:
  include:
    - stage: build
      script: 
        - docker-compose build
        - docker-compose run --rm php composer install --prefer-dist -n
    - stage: test
      script: docker-compose run --rm php vendor/phpspec/phpspec/bin/phpspec run
    - stage: test
      script: docker-compose run --rm php vendor/behat/behat/bin/behat
