version: "3.9"

services:
  core:
    build:
      context: .
      target: dev
    container_name: core
    volumes:
      - ./:/usr/src/app:rw,cached
      - ./.git:/tmp/.git
      - ./.githooks:/tmp/.githooks
