name: Build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: make
      - name: Build venv
        run: make poetry.update
      - name: Test
        run: make test
